### PR TITLE
Feature: Migrate to PyYAML for yaml generator.

### LINKED ISSUE #827: Plans to update swagger-ui package
# Feature Request

## Description

At the moment `drf-yasg` depends on a rather dated version `4.1.3` of `swagger-ui` (released in Dec 2021)
Since then, quite a few changes and bug fixes (including security issues) have been introduced: https://github.com/swagger-api/swagger-ui/compare/v4.1.3...v4.15.3

Do project maintainers have plans to use newer version of  `swagger-ui`?

Thanks

## Describe the solution you'd like

Ideally, update swagger-ui to the latest available version.

## Describe alternatives you've considered

N/A

### LINKED ISSUE #833: Use PyYAML instead of ruamel.yaml
## Description
PyYAML is the [default YAML serializer used in Django](https://github.com/django/django/blob/main/django/core/serializers/pyyaml.py) and also the suggested DRF [YAML renderer uses it](https://jpadilla.github.io/django-rest-framework-yaml/).

If someone uses these library with drf-yasg he is going to have two different YAML parsers, which is quite useless.

Also the concurrent library [drf-spectacular uses pyyaml](https://github.com/tfranzel/drf-spectacular/blob/24b8a9890d59900d102490a48e286d08cdcc7ab5/requirements/base.txt#L4).

## Proposal
If there is no particular reason in using `ruamel.yaml` (whcih as of now means "to support YAML 1.2") it will be better to replace it with `pyyaml` (for uniformity) or move it as an optional dependency (since YAML relies on a third party library which is not mandatory to generate a schema).

### PR DESCRIPTION
**Pull request by onegreyonewhite**
#### Changelog:
- Feature: Migrate to PyYAML for yaml generator.
- Chore: Update swagger ui and redoc dependencies.

Closes #833
Closes #827

Results (on some project with 180Kb schema `generate_swagger` and libyaml installed):
- `ruamel.yaml` -> from 1,582s to 1,828s
- `pyyaml` -> from 1,231s to 1,499s

### CODE REVIEW

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz As far as I can see it hasn't been released yet. Perhaps these changes will be useful for the next release. By the way, we are waiting for it.

**Comment by Quatters** [comment]
@JoelLefkowitz ping

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz are u still support this project? Should I fork this?

**Comment by JoelLefkowitz** [comment]
Yup, I'll have a look at merging this today

**Comment by JoelLefkowitz** [comment]
Thanks @onegreyonewhite

**Comment by onegreyonewhite** [comment]
> Thanks @onegreyonewhite

@JoelLefkowitz you're welcome) When are you going to release it?

**Comment by JoelLefkowitz** [comment]
> > Thanks @onegreyonewhite
> 
> @JoelLefkowitz you're welcome) When are you going to release it?

Will cut a new release in the next couple of days after a little more testing

**Pull request merged**
