### PR TITLE
fix map source mapping

### PR DESCRIPTION
**Pull request by PetrDlouhy**
There is mistake in link to the map js file which causes `whitenoise` in Djago 4.0 to fail with error:

```
Post-processing 'drf-yasg/redoc-old/redoc.min.js' failed!

Traceback (most recent call last):
  File "/home/petr/soubory/programovani/blenderkit/blenderhub_server/./manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'drf-yasg/redoc-old/redoc.min.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fd7578b2e80>.

The JS file 'drf-yasg/redoc-old/redoc.min.js' references a file which could not be found:
  drf-yasg/redoc-old/redoc.min.map
```

This MR fixes that.

### CODE REVIEW

**Review by jmateusousa — APPROVED** [review]

**Comment by PavanTatikonda** [comment]
@PetrDlouhy @axnsan12 Could you please help with the next steps for this fix and make new PyPI release

**Comment by PetrDlouhy** [comment]
@PavanTatikonda What steps could I do? I don't have any rights to this GitHub nor the PyPI repository.

**Comment by PavanTatikonda** [comment]
> @PavanTatikonda What steps could I do? I don't have any rights to this GitHub nor the PyPI repository.

@PetrDlouhy Oh ok, it looks like only @axnsan12 has permissions to cut a new release then. 
Anyway, thanks for providing the fix here!

**Comment by keyvanm** [comment]
Hey guys, bumping this. If this PR fixes #761 can we get it merged in?

**Comment by pandafy** [comment]
@axnsan12 ping!

**Comment by hardikns** [comment]
Can we pls get this in? @axnsan12

**Comment by JoelLefkowitz** [comment]
> Maybe @JoelLefkowitz can merge this?

I'll take a look, thanks for flagging

**Comment by JoelLefkowitz** [comment]
This is now present in 1.21.0

**Pull request merged**
