### PR TITLE
Feature: Add ``drf_yasg.inspectors.query.DrfAPICompatInspector``.

### LINKED ISSUE #856: get_schema_fields breaks when using django-filters after last update
# Bug Report

## Description

Used by class `CoreAPICompatInspector`
`get_schema_fields` is implemented on django-filters filter backend. By removing depentancy on `coreapi` in last 1.21.6 the function stopped working.

## Is this a regression?

yes it worked in 1.21.5

### PR DESCRIPTION
**Pull request by onegreyonewhite**
### Changelog:
* [Feature: Enable tests for django 4.2.](https://github.com/axnsan12/drf-yasg/commit/757db895dda5b480e46c18f50b457a491baa1604)
* [Feature: Add drf_yasg.inspectors.query.DrfAPICompatInspector.](https://github.com/axnsan12/drf-yasg/commit/dbf3548afa3ccc2f083a116338e0d45d20111ea2)
* [Feature: Provide to override default renderers via settings.](https://github.com/axnsan12/drf-yasg/commit/4edf7da2530a2d765ce38a9fa529a59277702502)
* [Docs: Add information how to override DEFAULT_SPEC_RENDERERS.](https://github.com/axnsan12/drf-yasg/commit/b19a1af32be2cd67524bf3056f98f98a7fec0237)

Fix #856

### CODE REVIEW

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz hey! This code moved from my project (https://github.com/vstconsulting/vstutils) and [fix regression](https://github.com/axnsan12/drf-yasg/issues/389#issuecomment-1599080055) with #854 on defaults. Tested with coreapi only with drf310. Other versions use new inspector.

May be should release new version.

**Review by pandafy — COMMENTED** [review]
Thanks for this patch @onegreyonewhite! 

I tested this in my project with the following packages and it fixed the issue. Kudos!

```
Django==4.2.2
djangorestframework==3.14.0
django-filter==23.2

```

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz should I fork it like independent project? Because looks like that you dont have enough time to maintain it.

**Comment by JoelLefkowitz** [comment]
@onegreyonewhite no thank you, I'm reviewing these changes more gradually and ensuring they don't break anything.

This is a mature project so the most important thing is stability and our test cases don't cover everything

**Comment by onegreyonewhite** [comment]
> @onegreyonewhite no thank you, I'm reviewing these changes more gradually and ensuring they don't break anything.
> 
> This is a mature project so the most important thing is stability and our test cases don't cover everything 

@JoelLefkowitz I'm going to cover it and send PRs periodically for peacefully sleeping at night))

This project important for vstutils, so I'm interested in the success of the project.

**Comment by JoelLefkowitz** [comment]
@onegreyonewhite Thanks, appreciate it

**Pull request merged**
