### PR TITLE
Fix: Provide support for enums in codecs.

### PR DESCRIPTION
**Pull request by onegreyonewhite**
We ran into bugs when using Enum objects in inspectors. Due to this problem, the schema could not be rendered via the generate_swagger command.

### CODE REVIEW

**Comment by onegreyonewhite** [comment]
I decided to immediately add tests for Python 3.11.

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz The project needs a goooood refactoring... ))

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz ping

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz 
> looks like unit tests failed for the python3.8, fancy having a look?

It was not the tests that were broken, but the documentation. I have no idea how it used to work. Perhaps this test was simply not checked before, and I fixed its launch.  Take a look.

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz can you approve CI run?

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz I finally found and solved the problem: the old mechanism does not work with the new tox. I think it is necessary to solve the problem of new tox in a separate PR.

Please, approve PR and check the code.

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz it becomes to hard to maintain this PR )) Started from enums and ended with refactoring, fixing bugs and CI and added support for feature django version.

I fixed dj-master tests. Django master branch bumped minimal python version to Python 3.10. In latest version was added check for uniq basename. That's was fixed and I think it's enough for this PR ;) Please, approve it and release it.

**Comment by JoelLefkowitz** [comment]
@onegreyonewhite Thanks for the contribution :)

**Comment by StevenMapes** [comment]
Also includes the equivalent changes from my PR for the older #836 so that's been closed now support is being tested :)

**Pull request merged**
