### PR TITLE
[WIP] add 'generate_swagger' management command

### PR DESCRIPTION
**Pull request by beaugunderson**
This is where I got to today with the management command; have not been able to test yet

### CODE REVIEW

**Comment by axnsan12** [comment]
Note - I added some suggestions here https://github.com/beaugunderson/drf-yasg/pull/1

**Comment by axnsan12** [comment]
@beaugunderson looks good to go for me. Do you have anything else you would like to add?

**Comment by axnsan12** [comment]
I'm going to go ahead and merge this, feel free to reopen if you have anything to add!

**Comment by beaugunderson** [comment]
@axnsan12 awesome, thank you!

**Pull request merged**
