### PR TITLE
[fix] Fixed map source mapping

### LINKED ISSUE #855: 1.21.6 - Missing redoc.min.map
# Bug Report

## Description

```
whitenoise.storage.MissingFileError: The file 'drf-yasg/redoc-old/redoc.min.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage
```

The `redoc.min.map` newly referenced [here](https://github.com/axnsan12/drf-yasg/blob/1.21.6/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js#L8) does not exist. 

There is `//# sourceMappingURL=redoc.min.js.map` in [1.21.5](https://github.com/axnsan12/drf-yasg/blob/1.21.5/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js#L8) which works fine.

## Is this a regression?

https://github.com/axnsan12/drf-yasg/issues/761

### PR DESCRIPTION
**Pull request by pandafy**
Closes #855

### CODE REVIEW

**Comment by pandafy** [comment]
Ping @axnsan12 @onegreyonewhite !

**Comment by pandafy** [comment]
Hey @JoelLefkowitz! Any idea why the CI is failing for Python 3.6 ?

**Comment by wbwlkr** [comment]
Hi @pandafy & @JoelLefkowitz, it is related to `runs-on: ubuntu-latest`.

As it is mentionned [here](https://github.com/actions/setup-python/issues/544#issuecomment-1324999753):
> The issue seems to simply be that there is no available build of Python 3.6 for ubuntu-22.04 (yet) 

The solution is to replace the line by `runs-on: ubuntu-20.04`.

**Comment by JoelLefkowitz** [comment]
@wbwlkr thanks for the suggestion. The workflow file has been updated already on the 1.21 branch. @pandafy if you bring you branch up to date with it the tests should run :)

**Comment by pandafy** [comment]
@JoelLefkowitz I have rebased the PR.

**Pull request merged**
