### PR TITLE
Add support for Django 3.2

### PR DESCRIPTION
**Pull request by NeOneSoft**
This PR was created in order to add support for Django 3.2

### CODE REVIEW

**Comment by NeOneSoft** [comment]
Hi @JoelLefkowitz, could you please help us to review this  PR for add support to Django 3.2? Thank you so much in advance!!

**Comment by JoelLefkowitz** [comment]
> Hi @JoelLefkowitz, could you please help us to review this PR for add support to Django 3.2? Thank you so much in advance!!

Happy to, thanks for your contribution 😊

**Review by JoelLefkowitz — APPROVED** [review]

**Comment by NeOneSoft** [comment]
@JoelLefkowitz Thank you for your support = )

**Comment by JoelLefkowitz** [comment]
After #739 is addressed, CI checks can run again and then a merge will be possible.

**Comment by JoelLefkowitz** [comment]
Since we've made changes to the tox.ini file in #741 we've included this change there rather than as two separate PRs. Thank you again @NeOneSoft for contributing.

**Comment by NeOneSoft** [comment]
Excelent @JoelLefkowitz !! Thank you so much!

**Pull request closed without merging**
